export const PAGINATION_CONSTANTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 10,
  MIN_PAGE_SIZE: 5,
  MAX_PAGE_SIZE: 100,
  SEARCH_DEBOUNCE_TIME: 300,
  CACHE_DURATION: 5 * 60 * 1000, // 5 minutes
} as const;
